version: '0.8.{build}'

branches:
  only:
    - master

image: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 14 2015 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\arcdps_uploader.sln

artifacts:
  - path: Release\d3d9_uploader.dll
    name: Arcdps Uploader
    
deploy:
  release: arcdps_uploader-v$(appveyor_build_version)
  description: Release
  provider: Github
  artifact: Arcdps Uploader
  draft: true