version: '0.8.{build}'

branches:
  only:
    - master

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 16 2019" -A x64 .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\arcdps_uploader.sln

after_build:
  - 7z a arcdps_uploader_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Release\d3d9_uploader.dll %APPVEYOR_BUILD_FOLDER%\LICENSE 

artifacts:
  - path: arcdps_uploader_%APPVEYOR_BUILD_VERSION%.zip
    name: ArcdpsUploader